language: python

python:
    - '3.6'

git:
    depth: 3
    quiet: true

install:
    - pip install pytest pyyaml

env:
  global:
    - CCONF_DIR=${TRAVIS_BUILD_DIR}/testconfig

before_script:
    - git clone https://github.com/COSIMA/1deg_jra55_iaf.git testconfig

script:
    - pytest test.py -s
