language: python

python:
    - '3.6'

git:
    depth: 3
    quiet: true

install:
    - pip install pytest pyyaml

env:
  global:

before_script:
    - git clone https://github.com/COSIMA/1deg_jra55_iaf.git testconfig

script:
    - CCONF_DIR=testfiles/access-esm-1.5 pytest test.py -s
    - CCONF_DIR=testfiles/access-om2-1deg_jra55_iaf pytest test.py -s
    - (cd testconfig && pytest -s ../test_shell_paths.py)
